#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public class DataBattleStage : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "StagePath")]
    public readonly string StagePath;
    [JsonProperty(PropertyName = "SpawnCount")]
    public readonly int SpawnCount;
    [JsonProperty(PropertyName = "UserBubbleCount")]
    public readonly int UserBubbleCount;
	
	public int Id => id;
    public bool IsEmpty => id == 0;
}
