#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public class DataBattleBoss : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "HP")]
    public readonly float HP;
    [JsonProperty(PropertyName = "PrefabPath")]
    public readonly string PrefabPath;
	
	public int Id => id;
    public bool IsEmpty => id == 0;
}
